// src/pages/ReportsPage.tsx
import React, { useEffect, useState } from 'react';
import { api } from '../services/apiClient';
import type { ReportSummary } from '../types';
import './ReportsPage.scss';

export const ReportsPage: React.FC = () => {
  const [reports, setReports] = useState<ReportSummary[]>([]);

  useEffect(() => {
    api
      .getReports()
      .then(setReports)
      .catch((e) => console.error('Reports load error', e));
  }, []);

  return (
    <section className="reports">
      <h2>Lite Reports</h2>
      <p>Download liquidity snapshots generated by the Lite AFP.</p>

      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Created</th>
            <th>Status</th>
            <th />
          </tr>
        </thead>
        <tbody>
          {reports.map((r) => (
            <tr key={r.id}>
              <td>{r.name}</td>
              <td>{r.createdAt}</td>
              <td>{r.status}</td>
              <td>
                <button className="link-btn" type="button">
                  Download
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  );
};
