import jsPDF from 'jspdf';
import type { Report } from '../types';

export function exportReportToPDF(report: Report) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Header
  doc.setFillColor(37, 99, 235); // Blue background
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('Insight Hunter Lite', 20, 25);
  
  doc.setFontSize(12);
  doc.text('Financial Report', 20, 33);
  
  // Report Title
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.text(report.title, 20, 55);
  
  // Report Details
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Period: ${report.period}`, 20, 65);
  doc.text(`Generated: ${new Date(report.generatedAt).toLocaleDateString()}`, 20, 72);
  doc.text(`Type: ${report.type.toUpperCase()}`, 20, 79);
  
  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 85, pageWidth - 20, 85);
  
  // Report Content
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  let yPos = 95;
  
  if (report.type === 'pl') {
    doc.text('Profit & Loss Statement', 20, yPos);
    yPos += 10;
    
    // Revenue Section
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('REVENUE', 20, yPos);
    doc.setFont('helvetica', 'normal');
    yPos += 8;
    
    if (report.data.revenue) {
      for (const [key, value] of Object.entries(report.data.revenue)) {
        doc.text(`  ${key}:`, 20, yPos);
        doc.text(`$${(value as number).toLocaleString()}`, pageWidth - 60, yPos, { align: 'right' });
        yPos += 7;
      }
    }
    
    yPos += 5;
    
    // Expenses Section
    doc.setFont('helvetica', 'bold');
    doc.text('EXPENSES', 20, yPos);
    doc.setFont('helvetica', 'normal');
    yPos += 8;
    
    if (report.data.expenses) {
      for (const [key, value] of Object.entries(report.data.expenses)) {
        doc.text(`  ${key}:`, 20, yPos);
        doc.text(`$${(value as number).toLocaleString()}`, pageWidth - 60, yPos, { align: 'right' });
        yPos += 7;
      }
    }
    
    yPos += 5;
    
    // Net Profit
    doc.setDrawColor(100, 100, 100);
    doc.line(20, yPos, pageWidth - 20, yPos);
    yPos += 8;
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('NET PROFIT:', 20, yPos);
    const netProfit = report.data.netProfit || 0;
    const profitColor = netProfit >= 0 ? [16, 185, 129] : [239, 68, 68];
    doc.setTextColor(profitColor[0], profitColor[1], profitColor[2]);
    doc.text(`$${netProfit.toLocaleString()}`, pageWidth - 60, yPos, { align: 'right' });
  }
  
  // Footer
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(8);
  doc.text('Generated by Insight Hunter Lite', pageWidth / 2, pageHeight - 10, { align: 'center' });
  
  // Save the PDF
  doc.save(`${report.title.replace(/\s+/g, '_')}_${report.period}.pdf`);
}

export function exportDashboardToPDF(kpis: any[], period: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('Insight Hunter Lite', 20, 25);
  
  doc.setFontSize(12);
  doc.text('Dashboard Report', 20, 33);
  
  // Report Title
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.text('Financial Dashboard', 20, 55);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Period: ${period}`, 20, 65);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 72);
  
  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 80, pageWidth - 20, 80);
  
  // KPIs
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text('Key Performance Indicators', 20, 95);
  
  let yPos = 110;
  doc.setFontSize(11);
  
  kpis.forEach((kpi, index) => {
    doc.setFont('helvetica', 'bold');
    doc.text(kpi.label, 20, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(kpi.value.toString(), pageWidth - 60, yPos, { align: 'right' });
    
    // Change indicator
    const changeColor = kpi.trend === 'up' ? [16, 185, 129] : kpi.trend === 'down' ? [239, 68, 68] : [100, 116, 139];
    doc.setTextColor(changeColor[0], changeColor[1], changeColor[2]);
    doc.setFontSize(9);
    doc.text(`${kpi.change > 0 ? '+' : ''}${kpi.change}%`, pageWidth - 60, yPos + 5, { align: 'right' });
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    yPos += 15;
  });
  
  // Footer
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(8);
  doc.text('Generated by Insight Hunter Lite', pageWidth / 2, pageHeight - 10, { align: 'center' });
  
  doc.save(`Dashboard_Report_${period.replace(/\s+/g, '_')}.pdf`);
}